/* ==========================================================================
   build-sitemap.mjs — generate sitemap.xml from data/index.json

   Hand-maintaining a sitemap guarantees it goes stale: a category added
   through /admin/ would never appear, and an unpublished one would keep
   being advertised to search engines. So it is generated from the same
   source of truth the pages are, and regenerated by the publish workflow.

   The site URL is read from SITE_URL if set, so a later custom domain needs
   no code change:

     node tools/build-sitemap.mjs
     SITE_URL=https://satvik.example node tools/build-sitemap.mjs
   ========================================================================== */

import { writeFile, readFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");

const DEFAULT_SITE = "https://mode-on-satvik.github.io/portfolio/";

/** Always ends with exactly one trailing slash, so joins are predictable. */
const site = (process.env.SITE_URL || DEFAULT_SITE).replace(/\/*$/, "/");

const read = (p) => readFile(path.join(ROOT, p), "utf8").then(JSON.parse);

const esc = (s) =>
  String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");

function entry({ loc, lastmod, priority, changefreq }) {
  return [
    "  <url>",
    `    <loc>${esc(loc)}</loc>`,
    lastmod ? `    <lastmod>${esc(lastmod)}</lastmod>` : null,
    changefreq ? `    <changefreq>${changefreq}</changefreq>` : null,
    `    <priority>${priority}</priority>`,
    "  </url>",
  ]
    .filter(Boolean)
    .join("\n");
}

async function main() {
  const index = await read("data/index.json");

  /* `updated` is a plain date in the JSON; sitemaps want W3C datetime, and a
     bare YYYY-MM-DD is valid. Fall back to today if it is missing. */
  const lastmod =
    typeof index.updated === "string" && /^\d{4}-\d{2}-\d{2}/.test(index.updated)
      ? index.updated.slice(0, 10)
      : new Date().toISOString().slice(0, 10);

  const live = (index.categories ?? [])
    .filter((c) => c.published !== false)
    .sort((a, b) => (a.order ?? 0) - (b.order ?? 0));

  const urls = [
    entry({ loc: site, lastmod, priority: "1.0", changefreq: "weekly" }),
    entry({ loc: `${site}about/`, lastmod, priority: "0.8", changefreq: "monthly" }),
    entry({ loc: `${site}contact/`, lastmod, priority: "0.8", changefreq: "monthly" }),
    ...live.map((cat) =>
      entry({
        loc: `${site}work/${cat.slug}/`,
        lastmod,
        priority: "0.9",
        changefreq: "weekly",
      })
    ),
  ];

  /* /admin/ and /404.html are deliberately absent: one is noindex and
     robots-disallowed, the other is an error page. */
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join("\n")}
</urlset>
`;

  await writeFile(path.join(ROOT, "sitemap.xml"), xml);
  console.log(`write  sitemap.xml  (${urls.length} urls, base ${site})`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
