/* ==========================================================================
   seed.mjs — generate data/index.json + data/categories/*.json

   Run once to scaffold, and safe to re-run: it will NOT overwrite a category
   file that already contains real photos. Placeholder entries exist so the
   whole site is viewable and layout-testable before a single photo is taken.

     node tools/seed.mjs
   ========================================================================== */

import { writeFile, readFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const DATA = path.join(ROOT, "data");
const CATS = path.join(DATA, "categories");

/* Copywriting register: confident, specific, professional — what a casting
   director expects. Never "cute", never pageant-ish, never written in the
   child's voice. Each blurb names the wardrobe, the setting, and what the
   look demonstrates. */
const CATEGORIES = [
  {
    slug: "formal-suit",
    title: "Formal Suit",
    subtitle: "Closeup & seated",
    blurb:
      "Tailored navy three-piece in studio. Direct-to-camera closeups and relaxed seated work — showing poise and stillness under lights.",
    setting: "Studio",
    year: "2026",
    aspect: [4, 5],
  },
  {
    slug: "sporty-basketball",
    title: "Sporty Basketball",
    subtitle: "Summer collection",
    blurb:
      "Outdoor court in natural light. Motion, mid-action expression and genuine energy — suited to athletic and activewear campaigns.",
    setting: "Location · outdoor court",
    year: "2026",
    aspect: [4, 5],
  },
  {
    slug: "ethnic-jacket-set",
    title: "Ethnic Jacket Set",
    subtitle: "Heritage tailoring",
    blurb:
      "Structured jacket set with traditional detailing. Editorial three-quarter and full-length frames against a clean backdrop.",
    setting: "Studio",
    year: "2026",
    aspect: [4, 5],
  },
  {
    slug: "ethnic-festive",
    title: "Ethnic Festive",
    subtitle: "Full-length celebration wear",
    blurb:
      "Festive dress photographed full-length with warm directional light. Movement, layered fabric and detail work for seasonal retail.",
    setting: "Studio · warm key",
    year: "2026",
    aspect: [4, 5],
  },
  {
    slug: "sporty-scooter",
    title: "Sporty Scooter",
    subtitle: "Prop-led outdoor session",
    blurb:
      "Scooter as working prop in open daylight. Confident interaction with equipment — useful for lifestyle, toy and outdoor brands.",
    setting: "Location · daylight",
    year: "2026",
    aspect: [4, 5],
  },
  {
    slug: "cultural-striped-shirt",
    title: "Cultural Striped Shirt",
    subtitle: "Relaxed portraiture",
    blurb:
      "Striped casualwear in soft natural light. Unposed smiles and easy eye contact — the warmest, most approachable set in the book.",
    setting: "Natural light",
    year: "2026",
    aspect: [4, 5],
  },
];

/* A neutral 1x1 WebP, used as the LQIP for placeholder tiles. Real photos get
   a genuine 24px blur generated by sharp in the publish workflow. */
const PLACEHOLDER_LQIP =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='4' height='5'%3E%3Crect width='4' height='5' fill='%231a1816'/%3E%3C/svg%3E";

/** Placeholder photo records so the masonry has varied shapes to lay out. */
function placeholderPhotos(cat, count) {
  // Deliberately mixed aspect ratios: the masonry must be verified against
  // portrait, landscape and square tiles, not a uniform grid.
  const shapes = [
    [1200, 1500], // 4:5 portrait
    [1200, 1600], // 3:4 portrait
    [1600, 1200], // 4:3 landscape
    [1200, 1200], // square
    [1200, 1800], // 2:3 tall
  ];

  return Array.from({ length: count }, (_, i) => {
    const [w, h] = shapes[i % shapes.length];
    return {
      id: `ph${String(i + 1).padStart(2, "0")}`,
      base: `images/${cat.slug}/placeholder-${String(i + 1).padStart(2, "0")}`,
      w,
      h,
      lqip: PLACEHOLDER_LQIP,
      formats: ["avif", "webp", "jpg"],
      widths: [400, 800, 1200, 2000],
      alt: `${cat.title} look ${i + 1} — placeholder, awaiting photography`,
      caption: `${cat.subtitle} · ${String(i + 1).padStart(2, "0")}`,
      order: i + 1,
      featured: i === 0,
      placeholder: true,
    };
  });
}

async function main() {
  await mkdir(CATS, { recursive: true });

  const indexCategories = [];

  for (const [i, cat] of CATEGORIES.entries()) {
    const file = path.join(CATS, `${cat.slug}.json`);
    let payload;

    // Preserve real content on re-run — only seed what is missing.
    if (existsSync(file)) {
      const existing = JSON.parse(await readFile(file, "utf8"));
      const hasReal = existing.photos?.some((p) => !p.placeholder);
      if (hasReal) {
        console.log(`skip   ${cat.slug} (has real photos)`);
        indexCategories.push(toIndexEntry(cat, existing, i));
        continue;
      }
      payload = { ...existing };
    }

    const photos = placeholderPhotos(cat, 6);
    payload = {
      slug: cat.slug,
      title: cat.title,
      subtitle: cat.subtitle,
      blurb: cat.blurb,
      setting: cat.setting,
      year: cat.year,
      published: true,
      order: i + 1,
      photos,
    };

    await writeFile(file, JSON.stringify(payload, null, 2) + "\n");
    console.log(`write  data/categories/${cat.slug}.json  (${photos.length} placeholders)`);
    indexCategories.push(toIndexEntry(cat, payload, i));
  }

  const index = {
    updated: new Date().toISOString().slice(0, 10),
    categories: indexCategories,
  };

  await writeFile(
    path.join(DATA, "index.json"),
    JSON.stringify(index, null, 2) + "\n"
  );
  console.log(`write  data/index.json  (${indexCategories.length} categories)`);
}

/** The homepage only needs a cover + count, never the full photo list. */
function toIndexEntry(cat, payload, i) {
  const photos = payload.photos ?? [];
  const cover = photos.find((p) => p.featured) ?? photos[0];

  return {
    slug: cat.slug,
    title: payload.title ?? cat.title,
    subtitle: payload.subtitle ?? cat.subtitle,
    blurb: payload.blurb ?? cat.blurb,
    count: photos.length,
    order: payload.order ?? i + 1,
    published: payload.published !== false,
    cover: cover
      ? {
          base: cover.base,
          w: cover.w,
          h: cover.h,
          lqip: cover.lqip,
          alt: cover.alt,
          // Carry the flag through: without it the homepage would emit real
          // <picture> tags for files that do not exist yet and 404 six times.
          ...(cover.placeholder ? { placeholder: true } : {}),
        }
      : null,
  };
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
